#!/usr/bin/env bash
# Usage: dev open <name>
# Summary: Opens a project for development
# Help: Changes into the project directory and opens a tmux session named after that project

set -e

# provide dev completions
if [ "$1" = "--complete" ]; then
  for name in $HOME/development/*; do
    echo ${name##*/}
  done

  exit
fi

name="$1"

cd "$HOME/development/$name"

if [ -n "$TMUX" ]; then
  tmux new-session -d -s "${name//./-}"
  tmux switch-client -t "${name//./-}"
else
  tmux new-session -s "${name//./-}"
fi
