#!/usr/bin/env bash
set -e

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: dv completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "dv-$COMMAND")"
if grep -i "^# provide dv completions" "$COMMAND_PATH" >/dv/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
